
FROM dpsim

RUN dnf -y install curl libcurl-devel openssl-devel
RUN pip3 install --upgrade pip
ENV PYCURL_SSL_LIBRARY openssl
RUN pip3 install pycurl

RUN useradd -m vc
COPY bin /home/vc/bin/
COPY setup.py /home/vc
COPY villas /home/vc/villas/
WORKDIR /home/vc

RUN python3.6 setup.py install

USER vc

CMD sleep 20 && villas-ctl -b "amqp://guest:guest@rabbitmq/%2F" --config config.json daemon
